base_url = "https://karenturman.com"
title = "Karen Turman"

compile_sass = false

build_search_index = false

[markdown]
insert_anchor_links = "none"

[extra]
avatar = "images/avatar.jpg"
social_links = [
    { name = "linkedin", url = "https://www.linkedin.com/in/karen-turman-2952a33a5/" },
    { name = "instagram", url = "https://www.instagram.com/turmanologie/" },
    { name = "graduation-cap", url = "https://harvard.academia.edu/KarenTurman" },
]
nav_links = [
    { label = "Teaching", path = "@/teaching/index.md", short_path = "/teaching" },
    { label = "Research", path = "@/research/index.md", short_path = "/research" },
    { label = "Dance Research", path = "@/dance-research/index.md", short_path = "/dance-research" },
    { label = "Dance Teaching", path = "@/dance-instruction/index.md", short_path = "/dance-instruction" },
    { label = "Resources", path = "@/resources/index.md", short_path = "/resources" },
]
